// Configure l'URL et la clé publique Supabase ici. Ne mets JAMAIS la clé service_role.
const CONFIG={url:"https://ylpyvuurujgkopoclaqx.supabase.co",anonKey:"sb_publishable_oFICs_KGLDnLI32yxQEZKw_jx8Im1AN"};
const ready=CONFIG.url.startsWith("https://")&&!CONFIG.url.includes("YOUR-PROJECT")&&CONFIG.anonKey.length>30&&!CONFIG.anonKey.includes("YOUR_SUPABASE");
const $=id=>document.getElementById(id);let db=null,session=null,profile=null;
$("year").textContent=new Date().getFullYear();
if(ready){db=window.supabase.createClient(CONFIG.url,CONFIG.anonKey);db.auth.onAuthStateChange((_e,s)=>{session=s;setTimeout(refresh,0)});refresh()}else $("configWarning").hidden=false;
$("navLogin").onclick=()=>$("account").scrollIntoView({behavior:"smooth"});
$("signup").onclick=async()=>{if(!db)return msg("authMsg","Configure Supabase via README.md.");let email=$("email").value.trim(),password=$("password").value;if(!email||password.length<8)return msg("authMsg","Entre un email valide et un mot de passe de 8 caractères minimum.");let{error}=await db.auth.signUp({email,password});msg("authMsg",error?error.message:"Compte créé. Vérifie ton email si une confirmation est demandée.")};
$("login").onclick=async()=>{if(!db)return msg("authMsg","Configure Supabase via README.md.");let{error}=await db.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});msg("authMsg",error?error.message:"Connecté.");await refresh()};
$("logout").onclick=async()=>{await db.auth.signOut();session=null;refresh()};
document.querySelectorAll(".buy").forEach(b=>b.onclick=()=>{$("plan").value=b.dataset.plan+"|"+b.dataset.price;$("account").scrollIntoView({behavior:"smooth"});if(!session)msg("authMsg","Connecte-toi pour demander ce forfait.")});
$("submit").onclick=async()=>{if(!db||!session)return msg("payMsg","Connecte-toi d'abord.");let ref=$("tx").value.trim();if(ref.length<4)return msg("payMsg","Entre la référence du reçu.");let[d,p]=$("plan").value.split("|").map(Number);let{error}=await db.from("subscription_orders").insert({user_id:session.user.id,plan_days:d,amount_usd:p,transaction_reference:ref,sender_name:$("sender").value.trim()||null,status:"pending"});msg("payMsg",error?error.message:"Demande envoyée. Ton abonnement reste en attente jusqu'à vérification réelle du transfert.");if(!error){$("tx").value="";await loadOrders()}};
$("refresh").onclick=loadAdmin;
async function refresh(){if(!db)return;let{data}=await db.auth.getSession();session=data.session;let on=!!session;$("auth").hidden=on;$("logged").hidden=!on;$("paymentForm").hidden=!on;$("loginHint").hidden=on;if(on){$("userEmail").textContent="Connecté : "+session.user.email;await loadOrders();let{data:p}=await db.from("profiles").select("role").eq("id",session.user.id).maybeSingle();profile=p;if(p&&p.role==="admin"){ $("admin").hidden=false;await loadAdmin()}else $("admin").hidden=true}else $("admin").hidden=true}
async function loadOrders(){let{data,error}=await db.from("subscription_orders").select("id,plan_days,amount_usd,status,created_at,expires_at").eq("user_id",session.user.id).order("created_at",{ascending:false});$("orders").innerHTML="";if(error){$("orders").textContent="Erreur de chargement. Vérifie le SQL.";return}if(!data.length){$("orders").textContent="Aucune demande.";return}data.forEach(o=>{let d=document.createElement("div");d.className="order";d.textContent=`Forfait ${o.plan_days} jours · ${o.amount_usd}$ · ${label(o.status)}${o.expires_at?" · Expire "+new Date(o.expires_at).toLocaleDateString("fr-FR"):""}`;$("orders").appendChild(d)})}
async function loadAdmin(){if(!db||!session||!profile||profile.role!=="admin")return;let{data,error}=await db.from("subscription_orders").select("id,plan_days,amount_usd,transaction_reference,sender_name,status").order("created_at",{ascending:false}).limit(100);$("adminOrders").innerHTML="";if(error){$("adminOrders").textContent=error.message;return}if(!data.length){$("adminOrders").textContent="Aucune demande.";return}data.forEach(o=>{let d=document.createElement("div");d.className="order";let t=document.createElement("div");t.textContent=`${o.plan_days} jours · ${o.amount_usd}$ · Réf. ${o.transaction_reference} · ${o.sender_name||"Expéditeur non précisé"} · ${label(o.status)}`;d.appendChild(t);if(o.status==="pending"){for(let[a,v]of [["approve","Confirmer paiement"],["reject","Refuser"]]){let b=document.createElement("button");b.textContent=v;b.className=a==="approve"?"gold":"";b.onclick=async()=>{let{error}=await db.rpc("admin_review_subscription",{p_order_id:o.id,p_action:a});msg("adminMsg",error?error.message:"Demande mise à jour.");await loadAdmin();await loadOrders()};d.appendChild(b)}}$("adminOrders").appendChild(d)})}
function label(s){return({pending:"En attente",active:"Actif",rejected:"Refusé",expired:"Expiré"})[s]||s}function msg(id,t){$(id).textContent=t}